services:
  domain_config.overrider:
    class: Drupal\domain_config\DomainConfigOverrider
    tags:
      - { name: config.factory.override}
    arguments: ['@domain.negotiator', '@config.factory', '@config.storage']

